networks:
  async_arch_edu:
    name: async_arch_edu

volumes:
  rabbit_data:
    name: async_arch_edu_rabbit_data

services:
  db:
    image: postgres:13
    container_name: async_arch_edu_postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PG_ROOT_PASSWORD}
      POSTGRES_USER: ${PG_ROOT_USER}
      APP_DB_USER: ${DB_USERNAME}
      APP_DB_PASSWORD: ${DB_PASSWORD}
      APP_DB_NAME: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      async_arch_edu:
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  # pgadmin:
  #     image: dpage/pgadmin4:5
  #     container_name: async_arch_edu_pgadmin
  #     env_file: .env
  #     environment:
  #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #         PGADMIN_LISTEN_PORT: 80
  #     ports:
  #     - ${PGADMIN_PORT}:80
  #     networks:
  #         async_arch_edu:
  #     volumes:
  #     - pgadmin:/var/lib/pgadmin
  #     depends_on:
  #     - db

  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
      - ${RABBITMQ_PORT}:5672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/mnesia/
