networks:
    async_arch_edu:
        name: async_arch_edu

volumes:
    dbdata:
        name: async_arch_edu_mysql_data
    rabbit_data:
        name: async_arch_edu_rabbit_data

services:
    mysql:
        image: mysql:8.0
        container_name: async_arch_edu_mysql
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            async_arch_edu:
    rabbit:
        image: rabbitmq:3.8-management
        hostname: rabbit
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - ${RABBITMQ_MANAGEMENT_PORT}:15672
            - ${RABBITMQ_PORT}:5672
        volumes:
            - rabbit_data:/var/lib/rabbitmq/mnesia/
